STOnlineShop/STOnlineShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EF;
using Model.ViewModel;
using STOnlineShop.Models;
using Model.Dao;
using System.Web.Script.Serialization;

namespace STOnlineShop.Controllers
{
    public class CartController : Controller
    {
        private const  string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
           
            var cart = Session[CartSession];
            
            var list = new List<CartItem>();

            
            if (cart != null)
            {
                list = (List<CartItem>)cart;
                

            }
            return View(list);
        }


        [HttpGet]
        public ActionResult Payment()
        {

            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string name, string phone, string address, string email)
        {
            var tran = new Transaction();
            tran.userName = name;
            tran.userPhone = phone;
            tran.userAddress = address;
            tran.userMail = email;

            try
            {
                var id = new TransactionDao().Insert(tran);
                var cart = (List<CartItem>)Session[CartSession];
                var orderDao = new OrderDao();
                foreach (var item in cart)
                {
                    var order = new Oder();
                    order.productId = item.Product.productId;
                    order.tranId = id;
                    order.price = item.Product.price;
                    order.quatity = item.Quantity;
                    order.size = item.Size;
                    order.createDay = DateTime.Now;
                    orderDao.Insert(order);

                }
            }
            catch(Exception ex)
            {
                return Redirect("/loi-thanh-toan");
            }

           
            return Redirect("/hoan-thanh");
        }
        
           
        public ActionResult Success()
        {


            return View();
        }

        




        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }


        public JsonResult Delete(int id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.productId == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

      






        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart =(List<CartItem>) Session[CartSession];


            foreach(var item in sessionCart){
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.productId == item.Product.productId);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                    item.Size = jsonItem.Size;
                }
                
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public ActionResult AddItem(int productId,int size, int quantity)
        {

            var product = new ProductDao().ViewDetail(productId);

            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.productId == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.productId == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.Product = product;
                    item.Size = size;
                    item.Quantity = quantity;

                    list.Add(item);
                }
                Session[CartSession] = list;
            }

            else
            {
                var item = new CartItem();
                item.Product = product;
                item.Size = size;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                Session[CartSession] = list;
            }


            return RedirectToAction("Index");
        }

        //public ActionResult AddItem(int productId, int quantity)
        //{
        //    var product = new ProductDao().ViewDetail(productId);
        //    var cart = Session[CartSession];
        //    if (cart != null)
        //    {
        //        var list = (List<CartItem>)cart;
        //        if (list.Exists(x => x.Product.productId == productId))
        //        {
        //            foreach (var item in list)
        //            {
        //                if (item.Product.productId == productId)
        //                {
        //                    item.Quantity += quantity;
        //                }
        //            }
        //        }
        //        else
        //        {
        //            var item = new CartItem();
        //            item.Product = product;
        //            item.Quantity = quantity;

        //            list.Add(item);
        //        }
        //        Session[CartSession] = list;
        //    }

        //    else
        //    {
        //        var item = new CartItem();
        //        item.Product = product;
        //        item.Quantity = quantity;
        //        var list = new List<CartItem>();

        //        list.Add(item);
        //        Session[CartSession] = list;
        //    }


        //    return RedirectToAction("Index");
        //}

        


    }
}

STOnlineShop/STOnlineShop/Views/Cart/Index.cshtml
@model List<STOnlineShop.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}

<div class="card">
    <h3>Cart Page</h3>
    
    @if (Model.Count!=0)
    {
        <table class="table table_bordered">
            <tr>

                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Size</th>
                <th>Hình ảnh</th>
                <th>Đơn giá</th>
                <th>Số lượng </th>
                <th>Thành tiền</th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                   
                    <td>@item.Product.productId</td>
                    <td>@item.Product.productName</td>
                    <td>@item.Size</td>
                    <td><img src="@item.Product.img" width="60" /> </td>
                    <td>@item.Product.priceSale</td>
                    <td><input  class="txtquantity" type="text"  data-size="@item.Size" data-id="@item.Product.productId" value="@item.Quantity"/></td>
                    <td>@(item.Product.price * item.Quantity)</td>
                    <td><a href="#" data-id="@item.Product.productId" class="btn-delete" >Xóa</a></td>
                </tr>
            }
          
        </table>

        <button id="btnContinue" class="btn">Tiếp tục mua hàng</button>
        <button id="btnUpdate" class="btn">Cập nhật giỏ hàng</button>
        <button id="btnDeleteAll" class="btn">Xóa giỏ hàng</button>
        <button id="btnPayment" class="btn">Thanh toán</button>

    }
    else
    {
        <p>Chưa có sản phẩm nào.</p>
    }

    <br>
   
</div>

<script>
    var cart = {
        init: function () {
            cart.regEvents();
        },
        regEvents: function () {
            $('#btnContinue').off('click').on('click', function () {
                window.location.href = "/Products/Shop";
            });

            $('#btnPayment').off('click').on('click', function () {
                window.location.href = "/thanh-toan";
            });

            $('#btnUpdate').off('click').on('click', function () {
                
                var listProduct = $('.txtquantity');
               
                var cartList = [];
                $.each(listProduct, function (i, item) {
                    cartList.push({
                        Product: {
                            productId: $(item).data('id')
                        },
                        Size: $(item).data('size'),
                        Quantity: $(item).val()
                    });
                       
                });


                $.ajax({
                    url:'/Cart/Update',
                    data: { cartModel: JSON.stringify(cartList) },
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = '/gio-hang-';
                        }
                    }
                });
            });


            $('#btnDeleteAll').off('click').on('click', function () {

              
                $.ajax({
                    url: '/Cart/DeleteAll',
                   
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = '/gio-hang-';
                        }
                    }
                });
            });



            $('.btn-delete').off('click').on('click', function (e) {
                e.preventDefault();

                $.ajax({
                    data: { id:$(this).data("id") },
                    url: '/Cart/Delete',

                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = '/gio-hang-';

                        }
                    }
                });
            });
        }
    }
    cart.init();
</script>

STOnlineShop/STOnlineShop/Views/Cart/Payment.cshtml
@model List<STOnlineShop.Models.CartItem>
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div>
    <table class="table table_bordered">
        <tr>

            <th>Mã sản phẩm</th>
            <th>Tên sản phẩm</th>
            <th>Size</th>
            <th>Hình ảnh</th>
            <th>Đơn giá</th>
            <th>Số lượng </th>
            <th>Thành tiền</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>

                <td>@item.Product.productId</td>
                <td>@item.Product.productName</td>
                <td>@item.Size</td>
                <td><img src="@item.Product.img" width="60" /> </td>
                <td>@item.Product.priceSale</td>
                <td><input class="txtquantity" type="text" data-size="@item.Size" data-id="@item.Product.productId" value="@item.Quantity" /></td>
                <td>@(item.Product.price * item.Quantity)</td>
                <td><a href="#" data-id="@item.Product.productId" class="btn-delete">Xóa</a></td>
            </tr>



        }
    </table>

</div>


<div class="section-group">

    @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
    {
        <div class="form-group">
            <label>Người nhận</label>
            <input name="name" class="form-control" />
        </div>
        <div class="form-group">
            <label>Điện thoại</label>
            <input name="phone" class="form-control" />
        </div>
        <div class="form-group">
            <label>Địa chỉ</label>
            <input name="address" class="form-control" />
        </div>
        <div class="form-group">
            <label>Email</label>
            <input name="email" class="form-control" />
        </div>
        <button type="submit" class="btn">Thanh toán</button>
    }

</div>

STOnlineShop/STOnlineShop/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    Bạn vừa mua hàng công!
</div>